Controller
Hermes-Internship/hermes-websites-backend-service pull request #10
Opened 2021-07-16 13:45 UTC by 911-Benedek-RobertGeorge

Activity and user controller and service

2021-07-17 10:55 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/controller/ActivityController.java
> +    private ActivityServiceInterface activityService;
Foloseste @Autowired cand declari serviceul sau in constructor

2021-07-17 10:57 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/controller/ActivityController.java
> +    public void save(@RequestBody Activity activity) {
E bine sa folosesti un dto ca sa primesti si sa trimiti date din si in frontend modifica peste tot unde folosesti Activity astfel incat sa folosesti un ActivityDto care sa contina strict datele de care ai nevoie

2021-07-17 10:57 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/controller/ActivityController.java
> +    @PutMapping("/update")
Ca aici. Foarte bine

2021-07-17 10:59 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/controller/ActivityControllerInterface.java
> +    void save(Activity activity);
Service-ul ar trebui sa primeasca drept argumente numai dto-uri cand vine vorba de tipuri de date complexe (adica nu int, String etc)

2021-07-17 11:00 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/controller/UserController.java
> +    public void save(@RequestBody User user){
Din nou. Foloseste Dtouri

2021-07-17 11:00 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/controller/UserControllerInterface.java
> +    void save(User user);
dto

2021-07-17 11:01 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/service/ActivityServiceInterface.java
> +    void save(Activity activity);
dto

2021-07-17 11:01 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/service/UserServiceInterface.java
> +    void update(UserDTO user);
Foarte bine

2021-07-17 11:01 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/service/serviceImplementation/ActivityServiceImplementation.java
> +    public void save(Activity activity) {
dto

2021-07-17 11:02 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/service/serviceImplementation/ActivityServiceImplementation.java
> +    public List<Activity> getAllActivities() {
List<Dto>

2021-07-17 11:03 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/service/serviceImplementation/ActivityServiceImplementation.java
> +    @Override
Foloseste @Transactional deasupra metodei. Altfel modificarile pe care le faci aici nu o sa se reflecte in baza de date

2021-07-17 11:03 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/service/serviceImplementation/UserServiceImplementation.java
> +    public void update(UserDTO user) {
foarte bine

2021-07-19 11:00 UTC, 911-Benedek-RobertGeorge reviewed
Am modificat, sper ca e ok acum, cu exceptiile si validarile cum ar trebui facut ?

2021-07-19 11:00 UTC, 911-Benedek-RobertGeorge reviewed
Am modificat, sper ca e ok acum, cu exceptiile si validarile cum ar trebui facut ?

2021-07-19 11:04 UTC, 911-Benedek-RobertGeorge reviewed
Am modificat, sper ca e bine acum. Cu exceptiile si validarile cum ar trebui sa facem ?

2021-07-20 07:17 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/controller/ActivityControllerInterface.java
> +    List<Activity> getAll();
Catre frontend ar trebui sa se trimita o lista de ActivityDto, nu o lista cu entitati

2021-07-20 07:18 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/controller/UserControllerInterface.java
> +    List<User> getAll();
Lista de UserDto

2021-07-20 07:21 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/service/serviceImplementation/ActivityServiceImplementation.java
> +        updatedActivity.setActivityLink(activity.getActivityLink());
Convertirea unui dto in entitate ar trebui sa fie facuta printr-o clasa separata. un UserMapper, nu in service. Service-ul nu trebuie sa stie sa converteasca din dto in entitate si invers

2021-07-21 17:31 UTC, McShenanigans requested changes

2021-07-21 17:31 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/controller/ActivityController.java
> +    public List<Activity> getAll() {
Trebuie sa trimita catre frontend lista de dtouri, nu de entitati

2021-07-21 17:31 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/controller/UserController.java
> +        return service.getAllUsers();
Si aici trebuie sa trimiti o lista de userDto

2021-07-21 17:31 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/service/ActivityServiceInterface.java
> +    List<Activity> getAllActivities();
trebuie sa trimita catre controller o lista de dto sau sa convertesti din entitate in dto in controller

2021-07-27 13:12 UTC, McShenanigans approved these changes

2021-07-28 14:18 UTC, fujinuji approved these changes

2021-07-28 14:18 UTC, fujinuji commented on src/main/java/ro/societateahermes/backendservice/controller/ActivityController.java
> +    @PutMapping("/update")
Incearca sa fii consectvent, la acel POST nu ai url mai specific (ceea ce recomand, facand o operatiune pe un obiect de baza, adica pentru cel pentru care este destinat controller-ul), iar aici ai PUT /activity/update ceea ce nu seaman ca mai sus.

Recomand sa ai PUT /activity

2021-07-28 21:50 UTC, merged