Create timeline branch
Hermes-Internship/hermes-websites-backend-service pull request #13
Opened 2021-07-20 07:26 UTC by Iri25

I created endpoints for events inside a timeline. I'm not sure if the mapping to DTO is ok, in the tutorial was the interface and the separate class for mapping

2021-07-21 06:20 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/controller/controllerImplementation/TimelineControllerImplementation.java
> +
Foarte bine 🎉 Ar mai trebui totusi un PutMapping ca sa actualizam un timeline si un GetMaping prin care luam un singur event dintr-un timeline

2021-07-21 06:25 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/entities/Timeline.java
> +}
Timeline-ul apartine de un singur event si este reprezentat de lista de activitati. Nu asa ar trebui sa arate modelul. Ar trebui sa modifici logica functionalitatii ca sa iti obtina timelineul in functie de id-ul evenimentului, nu al unui obiect Timeline

2021-07-21 06:26 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/entities/dto/EventDTO.java
> +}
👍👍

2021-07-21 06:26 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/mappers/EventMapperInterface.java
> +}
👍👍

2021-07-21 08:26 UTC, Iri25 commented on src/main/java/ro/societateahermes/backendservice/controller/controllerImplementation/TimelineControllerImplementation.java
> +
Am facut si PutMapping si GetMapping

2021-07-23 05:35 UTC, McShenanigans approved these changes

2021-07-23 05:54 UTC, McShenanigans requested changes, later dismissed

2021-07-23 05:54 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/controller/TimelineControllerInterface.java
> +    List<ActivityDTO> getAllActivityFromTimeline(Timeline timeline);
Ar trebui sa avem si un mod prin care sa obtinem un timeline in functie de id-ul eventului pentru care e site-ul. Faci pls un endpoint si pentru asta?

2021-07-25 11:51 UTC, McShenanigans commented on src/main/java/ro/societateahermes/backendservice/service/ActivityServiceInterface.java
> +    List<ActivityDTO> eventIsOngoing(Activity activity);
Aici de ce o metoda returneaza activity si cealalta activityDto?

2021-07-26 14:06 UTC, fujinuji approved these changes

2021-07-27 07:04 UTC, merged